### PR TITLE
Font outline

### PR DESCRIPTION
**Pull request by AEFeinstein**
### Description

Added a way to create outline fonts, which can be drawn over an existing font to outline it.

Add a way to have the mania renderer allocate and free its own fonts.

### Test Instructions

The outline font is used in the mania menu renderer.

### Ticket Links

#219

### Readiness Checklist
- [x] I have run `make format` to format the changes
- [x] I have compiled the firmware and the changes have no warnings
- [x] I have compiled the emulator and the changes have no warnings
- [x] I have run `make cppcheck` and checked that `cppcheck_result.txt` has no warnings for the changes
- [x] I have added doxygen comments to any code used by more than one Swadge mode. This includes `/*! \file` comments with Design Philosophy, Usage, and Example sections for new headers.
- [x] I have run `make docs` and checked that `doxy_warnings.txt` has no warnings for the new code

### CODE REVIEW

**Comment by dylwhich** [comment]
Looks good to me, except the item font here seems a little weird (the lowercase `a` and `e` get chopped a bit) - is this just because the outline is the same color as the background?
screenshot-1716166362242

**Comment by dylwhich** [comment]
> is this just because the outline is the same color as the background?

Wait, I can just try it and see! 
screenshot-1716166971599

Yeah, it looks fine with a non-background color even though the thin letters are still technically chopped up. So I think it's a non-issue for this PR.

**Comment by AEFeinstein** [comment]
Yeah, I made the decision to draw the outline on this inside edge of the font rather than the outside edge so that the outline font would be the exact same size and could be drawn without any offsets. The downside is that thin fonts don't take it so great.

**Comment by AEFeinstein** [comment]
Closed in favor of #236

**Pull request closed without merging**
